name: Basic CI Pipeline
# yml is used for pipeline/ workflows
# Trigger this pipeline on every push

on: [push] # in every push from this repo(.github\workflows) this pipeline executed

jobs:
    builds:
        runs-on: ubuntu-latest

        steps:
            - name: Build Stage
              run: echo "Application build successfully"
            - name: Test Stage
              run: echo "Test Cases passed"
            - name: Build deploy
              run: echo "Application deplyed successfully"